//go:build dev

package vite

import (
	"html/template"
	"log"
	"net/http"
	"os"
	"path/filepath"

	"github.com/olivere/vite"
)

var FS = os.DirFS("./frontend")
var publicFS = os.DirFS("./frontend/public")

func init() {
	IsDev = true

	Adapter = MakeViteAdapter(http.FileServerFS(FS), make_vite_handler)
}

func make_vite_handler(path string) http.Handler {
	config := vite.Config{
		FS:           FS,
		IsDev:        true,
		PublicFS:     publicFS,
		ViteURL:      "http://localhost:5173",
		ViteTemplate: vite.React,
	}

	tmpl, err := template.New("index").Parse(indexTmpl)
	if err != nil {
		log.Panic(err)
	}

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == path {
			viteFragment, err := vite.HTMLFragment(config)
			if err != nil {
				http.Error(w, "Error instantiating vite fragment", http.StatusInternalServerError)
				return
			}

			if err = tmpl.Execute(w, map[string]any{
				"Title": "Homepage", // TODO
				"Vite":  viteFragment,
			}); err != nil {
				http.Error(w, "Error executing template", http.StatusInternalServerError)
				return
			}
			return
		}

		// Serve the public files generated by Vite. By default, these files are
		// referenced in the DOM with a root-relative URL format (e.g. '/file.ext').
		http.ServeFileFS(w, r, publicFS, filepath.Base(r.URL.Path))
	})
}
