trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

pool:
  vmImage: ubuntu-latest

variables:
  IMAGE_NAME: 'stront'

stages:
  - stage: BuildAndTest
    jobs:
      - job: BuildAndTest
        steps:
          - script: |
              make build
            displayName: 'Building Code'

          - script: |
              make test
            displayName: 'Running Tests'

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'test-results.xml'
              testRunTitle: 'Publishing Backend Test Results'

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'frontend/vite-test-junit.xml'
              testRunTitle: 'Publishing Frontend Test Results'

  - stage: PublishImage
    dependsOn: BuildAndTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: PushContainerImage
        steps:
          - task: Docker@2
            inputs:
              command: 'login'
              containerRegistry: 'StrontContainerRegistry'

          - task: Docker@2
            inputs:
              command: 'buildAndPush'
              repository: 'stront'
              dockerfile: '**/Dockerfile'
              containerRegistry: 'StrontContainerRegistry'
              tags: |
                $(Build.BuildId)
                latest

  - stage: Deploy
    dependsOn: PublishImage
    condition: succeeded()
    # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: Deploy
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'StrontWebApp'
              appName: 'stront-rest'
              resourceGroupName: 'Stront'
              imageName: 'stront-hye4c0bebmcahjdy.azurecr.io/stront:$(Build.BuildId)'