services:
  frontend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      target: frontend-run
    volumes:
      - ./frontend/public:/app/frontend/public
      - ./frontend/src:/app/frontend/src
    environment:
      VITE_USE_POLLING: true
    ports:
      - "5173:5173"
    networks:
      - stront_net

  backend:
    depends_on:
      frontend:
        condition: service_started
    build:
      context: .
      target: backend-run
    environment:
      DB_CONNECTION_STRING: host=db user=admin password=password dbname=restaurant_db port=5432 sslmode=disable TimeZone=Australia/Sydney
      HOST_STRING: 0.0.0.0:3000
    volumes:
      - ./backend:/app/backend
    ports:
      - "3000:3000"
    networks:
      - stront_net
