services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - restaurant_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d restaurant_db"]
      interval: 5s
      retries: 5
      start_period: 5s

networks:
  restaurant_net: